[profile.default]
src = "."
out = "out"
libs = ["../lib", "tests/lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
sonic_testnet = "https://rpc.testnet.soniclabs.com"

[etherscan]
sonic_testnet = { key = "VTEYX6QC2DB9X3T94YW3VRVYI3W4V71TXG", url = "https://testnet.sonicscan.org/api" }



